URL_BASE = "https://www.saucedemo.com"
URL_BASE_ROOT = URL_BASE + "/"
URL_CART = "/cart"
URL_CART_ADD = "/add"
URL_INVENTORY = "/inventory.html"
URL_CART_HTML = "/cart.html"
URL_CHECKOUT_STEP1 = "/checkout-step-one.html"
URL_CHECKOUT_STEP2 = "/checkout-step-two.html"
URL_CHECKOUT_COMPLETE = "/checkout-complete.html"

E_MSG_LOGIN = "Epic sadface: Username and password do not match any user in this service"
E_MSG_LOGIN_USERNAME = "Epic sadface: Username is required"
E_MSG_LOGIN_PASSWORD = "Epic sadface: Password is required"
E_MSG_LOGIN_CARD = "Epic sadface: You can only access '/cart.html' when you are logged in."
E_MSG_LOGIN_LOCKED = "Epic sadface: Sorry, this user has been locked out."

E_MSG_CHECKOUT_FIRSTNAME = "Error: First Name is required"
E_MSG_CHECKOUT_LASTNAME = "Error: Last Name is required"
E_MSG_CHECKOUT_ZIPCODE = "Error: Postal Code is required"

SORT_AZ = "az"
SORT_ZA = "za"
SORT_PRICE_LOW = "lohi"
SORT_PRICE_HIGH = "hilo"
